//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACN_UD_Hoc_KHo_CTK37.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DACN_UD_Hoc_KHo_CTK37.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bài .
        /// </summary>
        public static string bai {
            get {
                return ResourceManager.GetString("bai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bài học số .
        /// </summary>
        public static string bai_so {
            get {
                return ResourceManager.GetString("bai_so", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap btnGoiY_ImageAn {
            get {
                object obj = ResourceManager.GetObject("btnGoiY.ImageAn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Câu .
        /// </summary>
        public static string cau_so {
            get {
                return ResourceManager.GetString("cau_so", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :.
        /// </summary>
        public static string dau_2_cham {
            get {
                return ResourceManager.GetString("dau_2_cham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        public static string dau_cham {
            get {
                return ResourceManager.GetString("dau_cham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /.
        /// </summary>
        public static string dau_cheo {
            get {
                return ResourceManager.GetString("dau_cheo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +.
        /// </summary>
        public static string dau_cong {
            get {
                return ResourceManager.GetString("dau_cong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : .
        /// </summary>
        public static string dau2chamvacach {
            get {
                return ResourceManager.GetString("dau2chamvacach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể kết nối dữ liệu..
        /// </summary>
        public static string error_connectionstring {
            get {
                return ResourceManager.GetString("error_connectionstring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gợi ý.
        /// </summary>
        public static string goi_y {
            get {
                return ResourceManager.GetString("goi_y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã hết câu hỏi của bài: .
        /// </summary>
        public static string het_cau_hoi {
            get {
                return ResourceManager.GetString("het_cau_hoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tin thấy từ này!.
        /// </summary>
        public static string khong_tim_thay {
            get {
                return ResourceManager.GetString("khong_tim_thay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nghe.
        /// </summary>
        public static string nghe {
            get {
                return ResourceManager.GetString("nghe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhấp để xem chi tiết ngữ pháp số: .
        /// </summary>
        public static string nha_de_xem_ngu_phap {
            get {
                return ResourceManager.GetString("nha_de_xem_ngu_phap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhấp để xem chi tiết bài số: .
        /// </summary>
        public static string nhan_de_xem_chi_tiet_bai_so {
            get {
                return ResourceManager.GetString("nhan_de_xem_chi_tiet_bai_so", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập câu trả lời!.
        /// </summary>
        public static string nhap_cau_trl {
            get {
                return ResourceManager.GetString("nhap_cau_trl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập từ cần tra!.
        /// </summary>
        public static string nhap_tu_can_tra {
            get {
                return ResourceManager.GetString("nhap_tu_can_tra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dừng.
        /// </summary>
        public static string stop {
            get {
                return ResourceManager.GetString("stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	.
        /// </summary>
        public static string tab {
            get {
                return ResourceManager.GetString("tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	- .
        /// </summary>
        public static string tab_daungang {
            get {
                return ResourceManager.GetString("tab_daungang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo.
        /// </summary>
        public static string thong_bao {
            get {
                return ResourceManager.GetString("thong_bao", resourceCulture);
            }
        }
    }
}
