//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;

namespace DACN_UD_Hoc_KHo_CTK37.DTO
{
	public partial class BaiHoc
    {
        [SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BaiHoc()
        {
            this.DanhMucs = new HashSet<DanhMuc>();
            this.LoiHayYDeps = new HashSet<LoiHayYDep>();
        }
    
        public int ID { get; set; }
        public string TenKHo { get; set; }
        public string TenViet { get; set; }
        public Nullable<int> IDHinh { get; set; }
    
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhMuc> DanhMucs { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoiHayYDep> LoiHayYDeps { get; set; }
    }
}
