//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;

namespace DACN_UD_Hoc_KHo_CTK37.DTO
{
	public partial class DanhMuc
    {
        [SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DanhMuc()
        {
            this.DanhMucCons = new HashSet<DanhMucCon>();
        }
    
        public int ID { get; set; }
        public string TenKHo { get; set; }
        public string TenViet { get; set; }
        public Nullable<int> IDBaiHoc { get; set; }
    
        public virtual BaiHoc BaiHoc { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhMucCon> DanhMucCons { get; set; }
    }
}
