//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACN_UD_Hoc_KHo_CTK37.DTO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HocKHoEntities : DbContext
    {
        public HocKHoEntities()
            : base("name=HocKHoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AmThanh> AmThanhs { get; set; }
        public virtual DbSet<BaiHoc> BaiHocs { get; set; }
        public virtual DbSet<BaiKhoa> BaiKhoas { get; set; }
        public virtual DbSet<CauHoi> CauHois { get; set; }
        public virtual DbSet<DamThoai> DamThoais { get; set; }
        public virtual DbSet<DanhMuc> DanhMucs { get; set; }
        public virtual DbSet<DanhMucCon> DanhMucCons { get; set; }
        public virtual DbSet<DichKHoViet> DichKHoViets { get; set; }
        public virtual DbSet<DichVietKHo> DichVietKHoes { get; set; }
        public virtual DbSet<Hinh> Hinhs { get; set; }
        public virtual DbSet<LoiHayYDep> LoiHayYDeps { get; set; }
        public virtual DbSet<LuyenTap> LuyenTaps { get; set; }
        public virtual DbSet<NguPhap> NguPhaps { get; set; }
        public virtual DbSet<TuVung> TuVungs { get; set; }
    }
}
